#!/bin/bash
# Dual Terminal Demo for ST-003
# This script shows the commands to run in two separate terminals

echo "=================================================="
echo "ST-003: Decentralized SOME/IP Discovery"
echo "Late Publisher Discovery (Subscriber First)"
echo "=================================================="
echo ""
echo "TERMINAL 1 - Subscriber (Consumer ECU)"
echo "=========================================="
echo ""
echo "cd /home/page/GitPlayground/pysomeip"
echo "source .venv/bin/activate"
echo "cd tinySOA/examples/system_tests/ST-003"
echo "python subscriber.py"
echo ""
echo "[Wait 2-3 seconds]"
echo ""
echo "TERMINAL 2 - Publisher (Provider ECU)"
echo "=========================================="
echo ""
echo "cd /home/page/GitPlayground/pysomeip"
echo "source .venv/bin/activate"
echo "cd tinySOA/examples/system_tests/ST-003"
echo "python publisher.py"
echo ""
echo "=================================================="
echo "Expected Behavior:"
echo "=================================================="
echo ""
echo "1. Subscriber sends SD Find (T+5s) on multicast"
echo "2. Publisher sends SD Offer in response"
echo "3. Subscriber sends SubscribeEventGroup unicast"
echo "4. Publisher sends SubscribeAck + initial notify"
echo "5. Subscriber receives message and test passes"
echo ""
echo "Each process maintains independent service table."
echo "No central registry - pure decentralized discovery."
echo ""
